# pull official base image
FROM python:3.8

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# copy project
COPY . /usr/src/app/

# set work directory
WORKDIR /usr/src/app

RUN apt-get update

RUN apt-get install gcc libmariadb-dev-compat libmariadb-dev -y

# run on the virual environment 
#RUN python -m venv /opt/venv
#ENV PATH="/opt/venv/bin:$PATH"
#RUN pip install -r requirements.txt

CMD ["python","manage.py","runserver", "0.0.0.0:8000"]